foundriesio/optee_os

- core/arch/arm/plat-imx/pm/imx7ulp_suspend.c
the nmi interrupt needs to be re-enabled in order to be able to exit
the poweroff state from the M4.
> [FIO internal] imx7ulp: exit CPUPOWEROFF state from NMI

- core/arch/arm/plat-imx/conf.mk
- core/arch/arm/plat-imx/registers/imx7ulp.h
Secure Non Volatile Storage: support must be enabled whenever RPMB_FS is configured
> SNVS support on imx7ulp

- core/arch/arm/kernel/thread.c
- core/core.mk
> se050: increase some stacks

- core/drivers/scp03_pta.c
- core/drivers/sub.mk
- core/include/crypto/crypto.h
- core/include/drivers/scp03_pta_client.h
- core/lib/libtomcrypt/aes.c
- core/lib/libtomcrypt/sub.mk
- lib/libnxpse050/adaptors/apis/apdu.c
- lib/libnxpse050/adaptors/apis/sss.c
- lib/libnxpse050/adaptors/include/se050.h
- lib/libnxpse050/adaptors/include/se050_apdu_apis.h
- lib/libnxpse050/adaptors/include/se050_sss_apis.h
- lib/libnxpse050/adaptors/include/se050_utils.h
- lib/libnxpse050/adaptors/utils/context.c
- lib/libnxpse050/adaptors/utils/scp_config.c
- lib/libnxpse050/core/aes.c
- lib/libnxpse050/core/scp03.c
- lib/libnxpse050/core/sub.mk
- lib/libnxpse050/se050/glue/i2c.c
> scp03: support late activation,  scp03 keys to/from secure storage, scp03_pta

- lib/libnxpse050/core/rsa.c
> rsa: vallidate buffer size

- core/lib/libtomcrypt/ecb.c
- lib/libnxpse050/adaptors/apis/sss.c
- lib/libnxpse050/adaptors/apis/user.c
- lib/libnxpse050/adaptors/include/se050_default_keys.h
- lib/libnxpse050/adaptors/include/se050_sss_apis.h
- lib/libnxpse050/adaptors/utils/info.c
- lib/libnxpse050/adaptors/utils/scp_config.c
- lib/libnxpse050/adaptors/utils/utils.c
- lib/libnxpse050/core/aes_ctr.c
- lib/libnxpse050/core/ecc.c
- lib/libnxpse050/core/rng.c
- lib/libnxpse050/se050/glue/wraps.c
- lib/libutils/ext/include/util.h
> se050 - clean up some warnings

- lib/libnxpse050/adaptors/utils/utils.c
An experimentally defined low transient memory threshold that when
reached causes all transient memory objects created during the session
to be deleted.
The first bit of the object identifier is used to differentiate
between persistent and transient objects.
> [FIO toup] libnxpse050: adaptors: low transient memory threshold

- core/arch/arm/plat-imx/crypto_conf.mk
- core/drivers/crypto/caam/acipher/caam_prime.c
> Release 74

- core/arch/arm/plat-imx/conf.mk
- core/arch/arm/plat-imx/registers/imx6-crm.h
- core/arch/arm/plat-imx/registers/imx6.h
- core/drivers/imx_i2c.c
> imx6ull - support i2c driver

- core/drivers/se050_cert_pta.c
- core/drivers/sub.mk
- core/include/crypto/crypto.h
- core/include/drivers/se050_cert_pta_client.h
- lib/libnxpse050/core/cert.c
- lib/libnxpse050/core/sub.mk
> Certificates

- core/arch/arm/plat-imx/conf.mk
- core/arch/arm/plat-imx/registers/imx8m.h
- core/drivers/imx_i2c.c
Signed-off-by: David Griego <david.griego@foundries.io>
> Add support for i2c for the imx8mqevk

- core/core.mk
Without these changes, my factory builds will fail.
In any case these are recommended op-tee guidelines so please merge.
> [FIO internal] core/core.mk: se050 force config guidelines

- core/tee/tee_rpmb_fs.c
> RPMB fixes backport from upstream

- ta/fiovb/include/ta_fiovb.h
> Secondary boot handling

- ta/fiovb/include/ta_fiovb.h
> 3.10+fio+secondary boot

- core/arch/arm/include/sm/psci.h
- core/arch/arm/plat-imx/pm/psci.c
- core/arch/arm/sm/psci.c
- core/drivers/imx_wdog.c
- core/include/drivers/imx_wdog.h
> SM SYSTEM_RESET2 support

- core/arch/arm/kernel/boot.c
- core/arch/arm/plat-imx/conf.mk
- core/arch/arm/plat-imx/crypto_conf.mk
- core/arch/arm/plat-imx/main.c
- core/drivers/crypto/caam/caam_ctrl.c
- core/drivers/imx_wdog.c
- mk/config.mk
> 3.10+fio+7ulp

- core/arch/arm/plat-imx/pm/psci.c
Add calls to power management framework. This framework only applies to
ARMv7 SoC.
Signed-off-by: Silvano di Ninno <silvano.dininno@nxp.com>
(cherry picked from commit a8677a18c4bd6ff4728e842b53e92d69b1fa962c)
Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>
> imx7ulp: fix suspending to vlls instead of vlps

- core/drivers/crypto/se050/adaptors/apis/sss.c
- core/drivers/crypto/se050/adaptors/utils/scp_config.c
- core/drivers/crypto/se050/crypto.mk
> 3.18+fio+se050 up

- core/drivers/crypto/se050/adaptors/utils/scp_config.c
- core/drivers/crypto/se050/core/rsa.c
- core/drivers/crypto/se050/crypto.mk
> 3.18+fio fixes

- core/drivers/crypto/se050/adaptors/apis/sss.c
Certain devices (depending on the applet) will use the common policies to for the object's read/write permissions.
Make sure both are supported.
> [FIO fromlist] crypto: se050: update policies

- core/mm/core_mmu.c
- ta/pkcs11/src/processing.h
> backportt 3.20+fio Fix conflicting types due to enum/integer mismatch

- core/drivers/crypto/se050/adaptors/utils/utils.c
Fix a broken sanity check - the error could never trigger but still the code was not correct as it could be writing to a null pointer.
> [FIO extras] drivers: crypto: se050: import ecc/rsa keys fix
