foundriesio/optee_os

core/drivers/crypto/caam/hal/imx_6_7/hal_jr.c
On the imx7ulp and during SDP boot the CAAM is not being unlocked
despite the request being made in the signed image (CSF section).
When this is the case, and if the CAAM is being locked with invalid
MID configs, the CAAM driver would fail to initialize as the MID
registers can not be reconfigured. And this would panic booting the
trust zone.
Ignoring this error and allowing the system to continue booting seems
to fulfill the software upgrade use case requirement (which is where we
use SDP for).
=> [FIO internal] caam: workaround CAAM locked by HAB during SDP boot

core/arch/arm/kernel/otp_stubs.c, core/arch/arm/plat-imx/drivers/imx_huk.c, core/include/kernel/tee_common_otp.h, core/tee/tee_rpmb_fs.c
Due to a problem in one of our releases, some imx7ulp boards were able
to access RPMB while still in the open state.
In the open state, CAAM provides a HUK that is different to the one
after the board has been closed.
This means that once the boards were closed, RPMB would not longer be
accessible.
The current commit addresses that situation.
=> [FIO internal] caam: imx7ulp: RPMB workaround for closed boards

core/arch/arm/kernel/otp_stubs.c, core/core.mk, lib/libnxpse050/core/huk.c
Report the SE050 unique die id (different than the HUK which in the
case of the IMX platform is being provided by the CAAM).
=> [FIO toup] libnxpse050: core: huk

lib/libnxpse050/se050/glue/smCom.c, lib/libnxpse050/se050/sub.mk
Since we can't enable the pthread lock used in the middleware
(smCom.c), the functionality using the lock must be replicated in the
glue.
=> [FIO toup] libnxpse050: glue: lock i2c transfers

core/lib/libtomcrypt/ecc.c, lib/libnxpse050/adaptors/apis/apdu.c, lib/libnxpse050/adaptors/apis/sss.c, lib/libnxpse050/adaptors/apis/user.c, lib/libnxpse050/adaptors/include/se050_apdu_apis.h, lib/libnxpse050/adaptors/include/se050_default_keys.h, lib/libnxpse050/adaptors/include/se050_sss_apis.h, lib/libnxpse050/adaptors/include/se050_user_apis.h, lib/libnxpse050/adaptors/include/se050_utils.h, lib/libnxpse050/adaptors/sub.mk, lib/libnxpse050/adaptors/utils/context.c, lib/libnxpse050/adaptors/utils/scp_config.c, lib/libnxpse050/adaptors/utils/utils.c, lib/libnxpse050/core/ecc.c
Tested in imx8evk
**Shared Secret:**
1)  lmp-device-register -n ecdh-imx8mmevk-001  -m /usr/lib/libsks.so.0.0 
2) pkcs11-tool --module /usr/lib/libsks.so.0.0 --keypairgen --key-type EC:prime256v1 --id 02 
3) pkcs11-tool --module /usr/lib/libsks.so.0.0 --read-object --type pubkey --id 02 -o /tmp/pub.der
4) pkcs11-tool --module /usr/lib/libsks.so.0.0  --id 01 --derive --input-file /tmp/pub.der -m ECDH1-DERIVE --output-file /tmp/bytes 
**SCP03 Rotation:**
Follow the op-tee configuration options defined in the commit and boot the bootloader.
> **NOTICE**: The SE050 scp03 keys can not be reset to its default values without having access to working values: ie, once the keys are rotated, the new keys MUST not be lost since there is no alternate procedure to reprogram them.
Signed-off-by: Jorge …
=> libnxpse050: ECC shared secret, SCP03 rotation, ECC sign/verify fixes

core/drivers/rng_pta.c, core/drivers/sub.mk, core/include/drivers/rng_pta_client.h
Add a Pseudo-TA to expose the crypto RNG from OPTEE.
This uses a generic call to crypto_rng_read() to supply the
random data.
=> [FIO toup] drivers: rng_pta

core/arch/arm/kernel/rpc_io_i2c.c, core/arch/arm/kernel/thread.c, core/arch/arm/plat-imx/crypto_conf.mk, core/core.mk, core/include/kernel/rpc_io_i2c.h, core/include/optee_rpc_cmd.h, lib/libnxpse050/se050/glue/i2c.c, mk/config.mk
1) use the CAAM RNG driver (since library symbols can not overload _weak symbols, the CAAM RNG driver will take precedence)
2) add retry field to the i2c master transfers (requires a kernel companion patch)
=> 3.10+fio.rel74 fixes

core/core.mk, lib/libnxpse050/core/rsa.c
RSA sign/verify without hash.
To test (similar for libsofthsm2.so)
sign:
pkcs11-tool  --module /usr/lib/libsks.so.0.0
--sign -m RSA-PKCS
--pin 87654321 --id 01
--input-file message
--output-file message.sig
-f openssl
verify:
pkcs11-tool  --module /usr/lib/libsks.so.0.0
--verify -m RSA-PKCS
--pin 87654321 --id 01
--signature-file message.sig
--input-file message
-f openssl
=> [FIO toup] libnxpse050: support TEE_ALG_RSASSA_PKCS1_V1_5

core/tee/tee_svc_cryp.c, lib/libnxpse050/adaptors/include/se050_utils.h, lib/libnxpse050/adaptors/utils/utils.c, lib/libnxpse050/core/ecc.c, lib/libnxpse050/core/rsa.c
Allow the criptoki client to request specific keys from the SE (ie,
those set during manufacturing).
The criptoki client would request the key using the label field at
creation time:
ie --label SE_XXXXXXXX (SE_ mark + 32 bit field representing the keyid
in hex)
pkcs11-tool --module /usr/lib/libsks.so.0.0
--keypairgen
--key-type RSA:4096
--id 01
--label SE_7F001010
--token-label aktualizr
--pin 87654321
=> RSA/ECC, request SE pre-provisioned keys

lib/libnxpse050/adaptors/apis/sss.c
Keys outside the user range for can not be deleted and therefore the
stack should not attempt to remove them.
=> [FIO toup] libnxpse050: remove error message

lib/libnxpse050/core/huk.c
The se050 unique identifier is larger than what op-tee expects and
therefore it might lose its uniqueness when truncated.
Create a digest from the unique identifier in an attempt to maintain
its uniqueness.
=> [FIO from upstream] se050: unique identifier

core/arch/arm/plat-imx/drivers/imx_snvs.c
These 2 patches address a flaw in the handling of the SNVS HPSR register on i.MX6 SoC.
The first patch was pulled from the 3.13 OP-TEE tree and the second was an addition to that patch needed for IMX6Q SoC.
=> Fio v3.10 imx6 sec fix

ta/fiovb/entry.c
```
Use intermediate temporary buffers instead of directly supplying
non-secure buffers to TEE_ReadObjectData()/TEE_CreatePersistentObject().
This fixes TA panics while accessing persistent objects:
E/TC:? 0 TA panicked with code 0xffff0001
E/LD:  Status of TA 22250a54-0bf1-48fe-8002-7b20f1c9c9b1
...
D/TC:? 0 user_ta_enter:176 tee_user_ta_enter: TA panicked with
code 0xffff0001
Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>
```
=> [FIO internal] ta: fiovb: copy data to temporary buffers

ta/fiovb/entry.c, ta/fiovb/include/ta_fiovb.h
Add support to delete values (objects).
Variables (tee objects) are allowed to be created with write, but it is
not currently possible to delete the object completely from tee after
it gets created.
This will also allow vendor specific values to be created as write-only,
which can only be updated if deleted and created from scratch.
=> [FIO internal] fiovb: add support to delete values

ta/fiovb/include/ta_fiovb.h
As done by u-boot (via environment), add upgrade_available to the
allowed persist list, so it can be used during the bootflow to avoid
bootcount updates when not really required.
=> [FIO internal] fiovb: add upgrade_available to persist list

core/lib/libtomcrypt/cbc.c, lib/libnxpse050/core/sub.mk
This symmetrict cipher performance was degrading RPMB access times.
With this change, 1 byte RPMB reads went down from 3 seconds to .07
=> [FIO internal] libnxpse050: route aes_cbc cipher to tomcrypt

core/arch/arm/kernel/boot.c
Latest boot code requires frag_id when generating dt fragments, so make
sure it is also exposed when CFG_OVERLAY_ADDR is used, otherwise it
generates a build failure.
To be squashed with "Support overlay at fix address and extend DTS" on a
rebase.
=> [FIO fixup] arm: boot: fix support for CFG_OVERLAY_ADDR

core/arch/arm/include/kernel/tz_ssvce_def.h, core/arch/arm/plat-imx/config/imx6sll.h, core/arch/arm/plat-imx/imx_pl310.c
The current tag/data ram, prefetch value is not the best value.
With this, the performance is not good. So retune the value
to match i.MX design to have good performance.
Also there is PL310 errata that we need to disable Double linefill
for version below r3p2 pl310.
Signed-off-by: Peng Fan <peng.fan@nxp.com>
Signed-off-by: Alessandro Di Chiara <alessandro.dichiara@nxp.com>
Signed-off-by: Michael Scott <mike@foundries.io>
=> [FIO extras] MLK-17962-3 core: arm: imx: tune PL310 configuration

ta/fiovb/entry.c
When an RPMB object cannot be created/opened/read the error
only states there was an error, but not what name it was trying
to use. This adds the object name to the error output.
Signed-off-by: Tim Anderson <tim.anderson@foundries.io>
=> [FIO internal] Add object name to error output

ta/fiovb/include/ta_fiovb.h
This adds a persist variable for fiovb for addressing
the case of an m4 update during secondary boot.
Signed-off-by: Tim Anderson <tim.anderson@foundries.io>
=> [FIO internal] Add persist variable m4_update

core/arch/arm/plat-imx/main.c, core/arch/arm/plat-imx/platform_config.h
Add dynamic shared memory configuration and enable it for the iMX
8mscale family.
This is based on the following patches from the NXP BSP tree:
- TEE-517 core: imx: Add dynamic shared memory configuration
- TEE-564 plat-imx: imx8mp enable DDR > 4 Gbytes
=> [FIO fromnxp] core: imx: add dynamic shared memory configuration

core/arch/arm/kernel/otp_stubs.c
There's no use case for Foundries where we want this stub implementation
for HUK in most i.MX devices, so don't define this weak function for
i.MX6/7/8M to cause a build break.
Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>
=> core: imx: remove HUK stub implementation for iMX8MP

core/drivers/imx/dcp/dcp.c
According to the i.MX6ULL manual, to read the UNIQUE_KEY from DCP
we must **not** set the OTP_KEY bit in ctrl0 and must use 0xFE for
the KEY_SELECT value in ctrl1 to retrieve the UNIQUE_KEY from
KEY ram where it is loaded just after SoC reset.
While ctrl1 was set correctly, OTP_KEY was being set in ctrl0.
Change proposed by Michael Scott <mike@foundries.io> at
https://github.com/OP-TEE/optee_os/pull/4094, but didn't end up being
part of the final changes.
=> [FIO toup] drivers: dcp: fix HUK support

core/drivers/crypto/se050/crypto.mk, core/drivers/crypto/se050/glue/i2c.c
Platforms with secure I2C buses (i.e: STM32MP1) or those with only
a secure element on the bus might prefer not to delegate the I2C
traffic to the REE.
=> drivers: se050: optional I2C access via trampoline

core/drivers/crypto/versal/authenc.c
Buffer sizes need to be 16 byte aligned or we risk hitting the PLM
AES DMA engine timeout (5 minutes).
This was observed excuting regression 1008.
For future reference debugging was helped with CFG_VERSAL_TRACE_MBOX.
=> versal: authenc: fix PLM DMA timeout

core/drivers/crypto/versal/authenc.c, core/drivers/crypto/versal/hash.c
In order to safely release the memory, the _SAFE version of the macro must be used
=> [FIO toup] crypto: versal: fix memory access after free

core/drivers/crypto/se050/adaptors/utils/scp_config.c
Prevents SCP03 rotation from using the derived keys unless RPMB is available.
This commit must be used particularly when
CFG_CORE_SE05X_SCP03_PROVISION_ON_INIT has been enabled.
=> [FIO internal]: : se050: scp03: prohibit derived keys without RPMB ready

core/drivers/crypto/se050/crypto.mk
Not supported by se050, disable following changes done for the CAAM crypto driver.
Proper fix requires software crypto fallback.
=> [FIO toup] drivers: se050: disable SM2_* when enabled

core/drivers/crypto/caam/acipher/caam_ecc.c, core/drivers/crypto/crypto_api/acipher/ecc.c, core/drivers/crypto/crypto_api/include/drvcrypt_acipher.h, core/drivers/crypto/se050/core/ecc.c, core/drivers/crypto/se050/crypto.mk, core/drivers/crypto/versal/ecc.c
This PR reverts the patch that disables ECC SM2_ support when the SE050 is enabled.
I implemented software fallback for the unsupported ECC algorithms in the SE050 crypto driver back in OPTEE_OS 3.22.0. 
So Instead of disabling SM2 support, lets just backport those patches.
Tested-by: Jorge Ramirez-Ortiz <jorge@foundries.io>
=> SM2 fallback
